### ISSUE TITLE
plugin fails with PSI4 1.0

### ISSUE THREAD

**Issue by wpoely86** [hande-qmc/fcidump#1]
With PSI4 1.0 I get (using the example in the README):

```
PSIO_ERROR: Can't find TOC Entry IWL Buffers
PSIO_ERROR: unit = 33, errval = 13
PSIO_ERROR: 13 (no such TOC entry)
An error has occurred python-side. Traceback (most recent call last):

  File "<string>", line 31, in <module>

  File "/user/scratch/gent/vsc403/vsc40307/EB/swalot/software/PSI4/1.0-intel-2016a-mt-Python-2.7.11/share/psi4/python/driver.py", line 446, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)

  File "/dev/shm/ward/fcidump/pymodule.py", line 52, in run_fcidump
    test_wfn = psi4.plugin('fcidump.so', ref_wfn)

RuntimeError: 
Fatal Error: PSIO Error
Error occurred in file: /dev/shm/ward/PSI4/1.0/intel-2016a-mt-Python-2.7.11/psi4-1.0/src/lib/libpsio/error.cc on line: 128
The most recent 5 function calls were:

psi::PsiException::PsiException(std::string, char const*, int)
psi::psio_error(unsigned int, unsigned int)
psi::PSIO::read(unsigned int, char const*, char*, unsigned long, psi::psio_address, psi::psio_address*)
psi::IWL::fetch()
void psi::iwl_integrals<psi::DPDFillerFunctor, psi::FrozenCoreAndFockRestrictedFunctor>(psi::IWL*, psi::DPDFillerFunctor&, psi::FrozenCoreAndFockRestrictedFunctor&)
```

**Comment by fdmalone** [comment]
Which combination of the fcidump plugin and psi4 are you using? I think psi4 1.0rc5 will work with the most recent version of fcidump.

**Comment by wpoely86** [comment]
This was done with psi4 1.0 (https://github.com/psi4/psi4/commit/6a9a71b5d435d033642e5953a30a379089520167) and d27dba5c9f84f18fe2d1813039d10dc95704e0b4

There is no 1.0rc5 version of psi4? Do you mean 0.5?

**Comment by fdmalone** [comment]
Sorry, I meant the release candidate number which is written in the output file (rc5). The sha1 is probably better. So I think the fcidump plugin needs updated again to be compatible with the most recent version of psi4 which you're using. I can reproduce the error with the newer version too. The plugin should work with https://github.com/psi4/psi4/commit/71ea2ea8ee142ee42541c589c42977fff2d3c381 , which is just an older version I had compiled.

**Comment by susilehtola** [comment]
PSI4 has evolved even more, and the plugin infrastructure has changed. Are you going to port fcidump to the new infrastructure?

**Comment by fdmalone** [comment]
I'm going to say yes, but I'm not sure when it'll happen.

**Comment by fdmalone** [comment]
fcidump now works with the new psi4 plugin infrastructure. Let us know if there are any issues.
