### ISSUE TITLE
Incompatibility in format

### ISSUE THREAD

**Issue by susilehtola** [hande-qmc/fcidump#3]
I was just informed by Peter Knowles in
 https://bitbucket.org/pjknowles/fci/issues/1/program-segfaults

that the orbital eigenvalues don't really belong in a FCIDUMP file. After all, they're unnecessary information, as they can be computed from the core Hamiltonian and the two electron integrals.

I think it'd be nice for fcidump to work with Knowles' FCI program which is available through the link above...

**Comment by ajwt** [comment]
Certainly that's true, assuming one knows the occupancy of the orbitals.  That is not always obvious and is not included 
in the FCIDUMP file and why I modified the format to include them (in a potentially backwards compatible manner) some 
years ago.  I would suggest two possibilities:

Easy: 1) An option in the fcidump plugin as to whether to include the orbital eigenvalues.
Harder: 2) Include the orbital occupancy in the header.

Either is basically fine.

Alex

**Comment by jsspencer** [comment]
1) is the right way to go. I'll do this today or tomorrow.
2) breaks reading in the header via a namelist.

**Comment by pjknowles** [comment]
It's an interesting irony that the README of this project complains mildly that other people have modified the format published in Comp. Phys. Commun. 54 75 (1989), but then you go ahead and do so yourself!  If it's any help, please help yourself to https://bitbucket.org/pjknowles/fcidump

**Comment by pjknowles** [comment]
It would be pretty easy to just write a list of the orbitals occupied in a reference function into the header, and this would not break programs that read the file.

**Comment by jsspencer** [comment]
@pjknowles Thanks for your comments and pointing us towards your own code. I think I actually backward engineered the format when originally writing this as I didn't have access to Comput Phys Commun for some reason. I have now noted we are amongst the offenders and (I think) pointed out the other discrepencies in #4. Perhaps we should add a strict compatibility option...

I'd rather not add the list of orbitals to the FCI header - this adds another incompatibility to codes that read the namelist in fortran (including your fci code and hande).
