### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by ajwt** [hande-qmc/fcidump#6]
(From an email):
Dear Dr. Alex

We are trying to compile the FCIDUMP plugin developed by James Spencer (https://github.com/hande-qmc/fcidump) to generate input files from PSI4 to the hande code. However, the available version (the last update is from 2016) is not compatible with the current version of PSi4.  Could you help us with this?

Thank you

**Comment by robertodr** [comment]
Psi4 (and also PySCF and HORTON, among the open source codes I know) can generate FCIDUMPs natively. I would update the `README.md` for this repository to point to these codes and then archive the repository.

**Comment by jsspencer** [comment]
Native support in PSI4 (thanks to @robertodr) is far better than this plugin. #7
